Update the version number
YOURLS/timezones pull request #11
Opened 2022-07-27 17:02 UTC by FreedomFighterSparrow

When 1.2 was released, the version number in the comment header remained "1.0", so PUNS kept thinking there's a newer version available, which is mildly annoying. I'm bumping the version number to 1.2.1 just for this.

2022-07-28 00:54 UTC, LeoColomb requested changes
Thanks, good catch!
That said the correct versioning would be 1.3 here 😊

2022-07-28 05:57 UTC, FreedomFighterSparrow commented
Why, though? This is only a patch, not even a bugfix, and there were no additional changes since the 1.2 release. Or am I missing something?

2022-07-28 09:56 UTC, LeoColomb commented
@FreedomFighterSparrow This plugin has a version based on `x.y` template, without "patch" number. 🙂

2022-07-28 13:54 UTC, FreedomFighterSparrow commented
Ah, that's a good reason. I force pushed an updated version.

2022-07-28 15:59 UTC, LeoColomb requested changes

2022-07-28 15:59 UTC, LeoColomb commented on plugin.php
> +Version: 1.2.1
```suggestion
Version: 1.3
```

2022-07-28 15:59 UTC, LeoColomb approved these changes

2022-07-28 17:13 UTC, FreedomFighterSparrow commented
I have no idea how I messed this up again. Thanks for fixing it :-)

2022-08-01 09:06 UTC, ozh approved these changes

2022-08-01 09:07 UTC, merged

2022-08-01 09:10 UTC, ozh commented
Thanks @FreedomFighterSparrow - new tag published as well